data_paths:
  raw_data: "data/Affairs.csv"

model_params:
  SVM:
    C: 1
    gamma: "scale"
    kernel: "linear"
  LogisticRegression:
    C: 0.1
    penalty: "l2"
    solver: "lbfgs"
  RandomForest:
    max_depth: 10
    min_samples_leaf: 4
    min_samples_split: 10
    n_estimators: 100

random_state: 42